image: python:3.9

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  REDIS_URL: 'redis://redis:6379/0'
  SERVER_URL: 'http://0.0.0.0:8000'
  SECRET_KEY: '2b38c28a4d952320bcabe59f061622785279c757db1e2e128b054635922136bd'
  SQLITE_URL: 'sqlite:///application.db'
  ACCESS_TOKEN_EXPIRE_MINUTES: 30

cache:
  paths:
    - .cache/pip
    - .venv/

before_script:
  - python -V
  - python -m venv .venv
  - source .venv/bin/activate
  - python -m pip install --upgrade pip
  - python -m pip install poetry
  - poetry install

stages:
  - lint
  - test

lint:
  stage: lint
  script:
    - flake8 --jobs 4 --statistics --show-source tests app
    - pylint --jobs 4 --rcfile=setup.cfg tests app
    - mypy tests app
    - black --skip-string-normalization --check tests app

test:
  stage: test
  script:
    - pytest -v tests
